version: '3.8'

services:
  db:
    image: postgres:14.13
    container_name: postgres-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - notes_network

volumes:
  postgres_data:

networks:
  notes_network:
